plugins {
    id "com.android.application"
}

android {
    namespace "com.diza.ai"
    compileSdk 35

    defaultConfig {
        applicationId "com.diza.ai"
        minSdk 26
        targetSdk 35
        versionCode 1
        versionName "1.0.0"
    }

    buildTypes {
        release {
            minifyEnabled false
            signingConfig signingConfigs.debug
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}
